// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8zoJhxMa_Rh7IQmILeJ97DBqZJbIJ1bo',
    appId: '1:666071215022:web:a668c919b5c947f17e763f',
    messagingSenderId: '666071215022',
    projectId: 'powerbi-cu',
    authDomain: 'powerbi-cu.firebaseapp.com',
    storageBucket: 'powerbi-cu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxoVJELZOwi_B9M9_8KuvWEYgtPOR0JsA',
    appId: '1:666071215022:android:4a6956aec0fd54d17e763f',
    messagingSenderId: '666071215022',
    projectId: 'powerbi-cu',
    storageBucket: 'powerbi-cu.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8zoJhxMa_Rh7IQmILeJ97DBqZJbIJ1bo',
    appId: '1:666071215022:web:be0e604136feaf727e763f',
    messagingSenderId: '666071215022',
    projectId: 'powerbi-cu',
    authDomain: 'powerbi-cu.firebaseapp.com',
    storageBucket: 'powerbi-cu.appspot.com',
  );
}
